### ISSUE TITLE
Texto para a tela de Login.

### ISSUE THREAD

**Issue by herculesra** [computacao-ufcg/eureca-frontend#103]

**Comment by herculesra** [comment]
[
![tela](https://user-images.githubusercontent.com/38411588/109718394-097db700-7b86-11eb-8742-0957ca976365.png)
](url)

**Comment by fubica** [comment]
O texto deve ser o seguinte:

Eureca é uma plataforma de apoio à gestão acadêmica que visa auxiliar as coordenações de cursos de graduação da UFCG em suas diversas atividades. A plataforma disponibiliza variadas informações sobre os discentes dos cursos, bem como oferece um leque de serviços de apoio às coordenações.

**Comment by fubica** [comment]
@herculesra favor modificar o código e fechar o issue.

**Comment by herculesra** [comment]
Feito.
