### ISSUE TITLE
Criar tela inicial da função "Estatísticas" (egressos pelo período escolhido no slider)

### ISSUE THREAD

**Issue by joaoarthurbm** [computacao-ufcg/eureca-frontend#5]
Esse gráfico deve aparecer em destaque do lado do resumo. Deve apresentar o número de egressos no eixo y e os períodos no eixo x. O eixo x é definido pela janela escolhida pelo usuário no slider. 

![Screen Shot 2020-07-31 at 17 48 21](https://user-images.githubusercontent.com/5099338/89076094-128b7900-d356-11ea-8de9-c30d7c619e05.png)

**Comment by fubica** [comment]
O texto do quadro de resumo é o seguinte (os valores numéricos devem ser apresentados com uma fonte um pouco maior que o texto):

Entre XXXX e XXXX foram graduados XXX discentes, com uma média de XXX graduados por período. O período XXXX foi o que mais teve egressos (XX), enquanto que o período XXXX foi o que teve menos (XX). O CRA médio dos egressos foi de X.XX, com mínimo de X.XX, máximo de X.XX e mediana de X.XX.

Um exemplo de "slider" pode ser visto aqui: https://www.jqueryscript.net/form/Price-Range-Slider-jQuery-UI.html. O usuário pode manipular para definir o período inicial e final das informações a serem apresentadas em outros elementos da página.
