### ISSUE TITLE
Label para tela de Empregadores

### ISSUE THREAD

**Issue by herculesra** [computacao-ufcg/eureca-frontend#85]
[] - Integrar o label gerado pelo Alumni-backend na tela de empregadores quando vai associar as empresas com os respectivos tipos (ONG's, Emp. Privadas e etc).
[] - A interface não será mais um "Select drop", mas sim um dropout gerado com os labels, removendo a necessidade do cliente clicar no select para observar as opções.
[] - Utilizar os dados do backend para mostrar as empresas que foram "Associadas". Isto será implementado esta semana no backend.

**Comment by ielepassos** [comment]
Tipos:

- Academia
- Empresa Privada
- Empresa Pública
- Empresa de Economia Mista
- Governo
- ONG
