### ISSUE TITLE
Tela VER MAIS

### ISSUE THREAD

**Issue by herculesra** [computacao-ufcg/eureca-frontend#87]
[] - Utilizar a nova rota do backend (ainda será implementada) para buscar os egressos de uma forma mais eficiente. 
    - Pesquisar por nome (Obrigatório)
    - Período de Admissão(Opcional)
    - Período de Graduação (Opcional)

**Comment by fubica** [comment]
Nenhum dos query params é obrigatório.

**Comment by herculesra** [comment]
Ok.
